url = "postgresql://postgres:Frontbigspin1@mp-scrape.c3q8nxhnui4e.us-east-1.rds.amazonaws.com:5432/mp_scrape"

[postgres]
host = "mp-scrape.c3q8nxhnui4e.us-east-1.rds.amazonaws.com"
port = 5432
database = "mp_scrape"
user = "postgres"
password = "Frontbigspin1"
