name: Deploy Lambda Functions

on:
  push:
    branches: [ main, lambda-testing ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        aws-region: us-east-1
        
    - name: Deploy orchestrator
      run: |
        zip -r orchestrator.zip src/
        aws lambda create-function \
          --function-name mp-scraper-orchestrator \
          --runtime python3.11 \
          --handler src.lambda.orchestrator.lambda_handler \
          --role ${{ secrets.AWS_LAMBDA_ROLE_ARN }} \
          --zip-file fileb://orchestrator.zip || \
        aws lambda update-function-code \
          --function-name mp-scraper-orchestrator \
          --zip-file fileb://orchestrator.zip

    - name: Deploy worker
      run: |
        zip -r worker.zip src/
        aws lambda create-function \
          --function-name mp-scraper-worker \
          --runtime python3.11 \
          --handler src.lambda.worker.lambda_handler \
          --role ${{ secrets.AWS_LAMBDA_ROLE_ARN }} \
          --zip-file fileb://worker.zip || \
        aws lambda update-function-code \
          --function-name mp-scraper-worker \
          --zip-file fileb://worker.zip