name: Deploy Lambda Functions

on:
  push:
    branches: [ main, user-input ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Create ECR repository if not exists
      run: |
        aws ecr create-repository \
          --repository-name mp-scraper \
          --image-scanning-configuration scanOnPush=true || true

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: mp-scraper
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
  
    - name: Delete existing event source mappings
      run: |
        # Get and delete orchestrator mappings
        MAPPINGS=$(aws lambda list-event-source-mappings --function-name mp-scraper-orchestrator --query 'EventSourceMappings[*].UUID' --output text || true)
        for UUID in $MAPPINGS; do
          aws lambda delete-event-source-mapping --uuid $UUID || true
        done
        
        # Get and delete worker mappings
        MAPPINGS=$(aws lambda list-event-source-mappings --function-name mp-scraper-worker --query 'EventSourceMappings[*].UUID' --output text || true)
        for UUID in $MAPPINGS; do
          aws lambda delete-event-source-mapping --uuid $UUID || true
        done
        
        # Get and delete retry worker mappings
        MAPPINGS=$(aws lambda list-event-source-mappings --function-name mp-scraper-retry-worker --query 'EventSourceMappings[*].UUID' --output text || true)
        for UUID in $MAPPINGS; do
          aws lambda delete-event-source-mapping --uuid $UUID || true
        done

    - name: Delete existing functions
      run: |
        aws lambda delete-function --function-name mp-scraper-orchestrator || true
        aws lambda delete-function --function-name mp-scraper-worker || true
        aws lambda delete-function --function-name mp-scraper-retry-worker || true

    - name: Create SQS Queue if not exists
      run: |
        aws sqs create-queue --queue-name mp-scraper-queue || true

    - name: Create initiate-orchestrator-queue if not exists
      run: |
        aws sqs create-queue --queue-name initiate-orchestrator-queue || true
          
    - name: Create DLQ Queue
      run: |
        aws sqs set-queue-attributes \
          --queue-url https://sqs.us-east-1.amazonaws.com/855154218477/mp-scraper-dlq \
          --attributes '{
            "VisibilityTimeout": "900"
          }'
        
    - name: Update main queue with DLQ
      run: |
        QUEUE_URL=$(aws sqs get-queue-url --queue-name mp-scraper-queue --output text --query 'QueueUrl')
        DLQ_URL=$(aws sqs get-queue-url --queue-name mp-scraper-dlq --output text --query 'QueueUrl')
        DLQ_ARN=$(aws sqs get-queue-attributes --queue-url $DLQ_URL --attribute-names QueueArn --query 'Attributes.QueueArn' --output text)
        
        aws sqs set-queue-attributes \
          --queue-url $QUEUE_URL \
          --attributes '{
            "RedrivePolicy": "{\"deadLetterTargetArn\":\"'$DLQ_ARN'\",\"maxReceiveCount\":3}",
            "VisibilityTimeout": "900",
          }'
    - name: Set initiate-orchestrator-queue attributes
      run: |
        QUEUE_URL=$(aws sqs get-queue-url --queue-name initiate-orchestrator-queue --output text --query 'QueueUrl')
        aws sqs set-queue-attributes \
          --queue-url $QUEUE_URL \
          --attributes '{
            "VisibilityTimeout": "900"
          }'

    - name: Update initiate-orchestrator-queue with DLQ
      run: |
        QUEUE_URL=$(aws sqs get-queue-url --queue-name initiate-orchestrator-queue --output text --query 'QueueUrl')
        DLQ_URL=$(aws sqs get-queue-url --queue-name mp-scraper-dlq --output text --query 'QueueUrl')
        DLQ_ARN=$(aws sqs get-queue-attributes --queue-url $DLQ_URL --attribute-names QueueArn --query 'Attributes.QueueArn' --output text)
        
        aws sqs set-queue-attributes \
          --queue-url $QUEUE_URL \
          --attributes '{
            "RedrivePolicy": "{\"deadLetterTargetArn\":\"'$DLQ_ARN'\",\"maxReceiveCount\":3}",
            "VisibilityTimeout": "900"
          }'

    - name: Deploy worker function
      run: |
        aws lambda create-function \
          --function-name mp-scraper-worker \
          --package-type Image \
          --code ImageUri=${{ steps.login-ecr.outputs.registry }}/mp-scraper:latest \
          --role ${{ secrets.AWS_LAMBDA_ROLE_ARN }} \
          --environment '{"Variables": {
              "POSTGRES_HOST": "${{ secrets.POSTGRES_HOST }}",
              "POSTGRES_DB": "${{ secrets.POSTGRES_DB }}",
              "POSTGRES_USER": "${{ secrets.POSTGRES_USER }}",
              "POSTGRES_PASSWORD": "${{ secrets.POSTGRES_PASSWORD }}",
              "POSTGRES_PORT": "${{ secrets.POSTGRES_PORT }}",
              "IPROYAL_USERNAME": "${{ secrets.IPROYAL_USERNAME }}",
              "IPROYAL_PASSWORD": "${{ secrets.IPROYAL_PASSWORD }}",
              "MP_USERNAME": "${{ secrets.MP_USERNAME }}",
              "MP_PASSWORD": "${{ secrets.MP_PASSWORD }}",
              "OPENAI_API_KEY": "${{ secrets.OPENAI_API_KEY }}"
          }}' \
          --timeout 900 \
          --memory-size 900 \
          --image-config '{"Command": ["src.lambdas.worker.lambda_handler"]}'

    - name: Set worker concurrency
      run: |
        aws lambda put-function-concurrency \
          --function-name mp-scraper-worker \
          --reserved-concurrent-executions 100

    - name: Deploy retry worker function
      run: |
        aws lambda create-function \
          --function-name mp-scraper-retry-worker \
          --package-type Image \
          --code ImageUri=${{ steps.login-ecr.outputs.registry }}/mp-scraper:latest \
          --role ${{ secrets.AWS_LAMBDA_ROLE_ARN }} \
          --environment '{
            "Variables": {
              "MP_USERNAME": "${{ secrets.MP_USERNAME }}",
              "MP_PASSWORD": "${{ secrets.MP_PASSWORD }}",
              "IPROYAL_USERNAME": "${{ secrets.IPROYAL_USERNAME }}",
              "IPROYAL_PASSWORD": "${{ secrets.IPROYAL_PASSWORD }}",
              "POSTGRES_HOST": "${{ secrets.POSTGRES_HOST }}",
              "POSTGRES_DB": "${{ secrets.POSTGRES_DB }}",
              "POSTGRES_USER": "${{ secrets.POSTGRES_USER }}",
              "POSTGRES_PASSWORD": "${{ secrets.POSTGRES_PASSWORD }}",
              "POSTGRES_PORT": "${{ secrets.POSTGRES_PORT }}",
              "OPENAI_API_KEY": "${{ secrets.OPENAI_API_KEY }}"
            }
          }' \
          --timeout 900 \
          --memory-size 900 \
          --image-config '{"Command": ["src.lambdas.retry_worker.lambda_handler"]}'
        
    - name: Set retry worker concurrency
      run: |
        aws lambda put-function-concurrency \
          --function-name mp-scraper-retry-worker \
          --reserved-concurrent-executions 100

    - name: Update Lambda IAM Role
      run: |
        aws iam put-role-policy \
          --role-name new_lambda_role \
          --policy-name sqs-permissions \
          --policy-document '{
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Action": [
                  "sqs:ReceiveMessage",
                  "sqs:DeleteMessage",
                  "sqs:GetQueueAttributes",
                  "sqs:SendMessage",
                  "sqs:SendMessageBatch"
                ],
                "Resource": [
                  "arn:aws:sqs:us-east-1:855154218477:initiate-orchestrator-queue",
                  "arn:aws:sqs:us-east-1:855154218477:mp-scraper-queue",
                  "arn:aws:sqs:us-east-1:855154218477:mp-scraper-dlq"
                ]
              }
            ]
          }'

    - name: Deploy orchestrator function
      run: |
        aws lambda create-function \
          --function-name mp-scraper-orchestrator \
          --package-type Image \
          --code ImageUri=${{ steps.login-ecr.outputs.registry }}/mp-scraper:latest \
          --role ${{ secrets.AWS_LAMBDA_ROLE_ARN }} \
          --environment '{"Variables": {
              "QUEUE_URL": "${{ secrets.SQS_URL }}",
              "NEW_SCRAPE_QUEUE_URL": "${{ secrets.NEW_SCRAPE_QUEUE_URL }}",
              "IPROYAL_USERNAME": "${{ secrets.IPROYAL_USERNAME }}",
              "IPROYAL_PASSWORD": "${{ secrets.IPROYAL_PASSWORD }}"
          }}' \
          --timeout 900 \
          --memory-size 900 \
          --image-config '{"Command": ["src.lambdas.orchestrator.lambda_handler"]}'

    - name: Configure SQS Trigger for Orchestrator
      run: |
        aws lambda create-event-source-mapping \
          --function-name mp-scraper-orchestrator \
          --event-source-arn arn:aws:sqs:us-east-1:855154218477:initiate-orchestrator-queue \
          --batch-size 1 || true
    - name: Configure SQS Trigger for Retry Worker
      run: |
        aws lambda create-event-source-mapping \
          --function-name mp-scraper-retry-worker \
          --event-source-arn arn:aws:sqs:us-east-1:855154218477:mp-scraper-dlq \
          --batch-size 1 || true
    - name: Configure SQS Trigger for Worker
      run: |
        aws lambda create-event-source-mapping \
          --function-name mp-scraper-worker \
          --event-source-arn arn:aws:sqs:us-east-1:855154218477:mp-scraper-queue \
          --batch-size 1 || true

    - name: Add SQS Permission to Orchestrator
      run: |
        aws lambda add-permission \
          --function-name mp-scraper-orchestrator \
          --statement-id SQSInvoke \
          --action lambda:InvokeFunction \
          --principal sqs.amazonaws.com \
          --source-arn arn:aws:sqs:us-east-1:855154218477:initiate-orchestrator-queue || true

    - name: Add SQS Permission to Retry Worker
      run: |
        aws lambda add-permission \
          --function-name mp-scraper-retry-worker \
          --statement-id SQSDLQInvoke \
          --action lambda:InvokeFunction \
          --principal sqs.amazonaws.com \
          --source-arn arn:aws:sqs:us-east-1:855154218477:mp-scraper-dlq || true

    - name: Add SQS Permission to Worker
      run: |
        aws lambda add-permission \
          --function-name mp-scraper-worker \
          --statement-id SQSInvoke \
          --action lambda:InvokeFunction \
          --principal sqs.amazonaws.com \
          --source-arn arn:aws:sqs:us-east-1:855154218477:mp-scraper-queue || true  